install.packages("rpart.plot")
library(rpart)
library(rpart.plot)
data = read.csv("Mark.csv")
tree <- rpart(Mark ~ Subject+Grade,data)
a <- data.frame(Subject=c("English"),Grade=c("O"))
result <- predict(tree,a)
print(result)
rpart.plot(tree)
tree <- rpart(Subject ~ Mark+Grade,data)
a <- data.frame(Mark=c(59),Grade=c("C"))
result <- predict(tree,a)
print(result)
rpart.plot(tree)
